Board of Development:
  Backlog:
    - 'backlog'
  Priorities:
    - 'important'
  Development:
    - 'in progress'
  Test:
    - 'in test'
  CodeReview:
    - 'waiting'
  ReadyToProduction:
    - 'completed'
