version: '3.9'
services:
    database:
        container_name: mongodb-tablerise
        image: mongo:5
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=secret

    database-test:
        container_name: mongodb-tablerise-test
        image: mongo:5
        ports:
            - 27018:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=secret

volumes:
    mongodb-tablerise-volume:
    mongodb-tablerise-test-volume:
