name: Comment Errors
on:
  workflow_run:
    workflows:
      - Continuous Delivery Action
    types: [ completed ]

jobs:
  comment-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: quipper/comment-failure-action@v0.1.1
        with:
            api-token: ${{ github.token }}